### ISSUE TITLE
ITM

### ISSUE THREAD

**Issue by emaster654** [akte182/Graficacion#1]
Profe, le quería comentar que varios de nuestro maestros ya nos están cancelando clases esta semana, y con casi todos esos maestros comenzaremos a trabar en plataformas en línea, y queríamos ver con usted cómo sería la situación, al menos de esta semana

**Comment by emaster654** [comment]
@akte182 Como quedariamos?

**Comment by akte182** [comment]
Hola, yo de momento el día de mañana asistiré justo con el propósito de ponernos de acuerdo, si es la única clase a la que tienen que ir no vayan y les dejare instrucciones por aqui en github. Pero si los hacen ir dense una vuelta por la clase.

**Comment by emaster654** [comment]
va que va, profe que de echo era la única clase que nos faltaba por confirmar
